package image.model;


public enum FlowState {

    PROCESS_IMAGE_SCHEDULED,
    PROCESS_IMAGE_FINISHED,
    PROCESS_IMAGE_FAILED,
    EXPOSE_IMAGE_SCHEDULED,
    EXPOSE_IMAGE_FINISHED,
    EXPOSE_IMAGE_FAILED,
    PROCESS_EO_STARTED,
    PROCESS_EO_FINISHED,
    PROCESS_EO_FAILED;

}
